---
title: "V4 Camera with Updated Firmware"
output: html_document
date: "2025-10-22"
---

```{r setup, include=FALSE}
library(DBI)
library(sswids)
library(stringr)
library(gridExtra)
library(ggplot2)
library(dplyr)

sswids::connect_to_sswidb(db_version = 'PROD')

PartnerV4UpdateFirmware <- DBI::dbGetQuery(conn, "SELECT DISTINCT
    g83100.sswi_photo.camera_firmware_text,
    g83100.sswi_photo.upload_batch_seq_no,
    g83100.sswi_camera.dnr_inventory_id,
    g83100.sswi_camera.camera_seq_no AS camera_seq_no1,
    g83100.sswi_cam_part_grid_xref.partner_seq_no,
    g83100.sswi_partner.first_name,
    g83100.sswi_partner.last_name,
    g83100.sswi_partner.partner_comment_text,
    g83100.sswi_batch.start_active_date,
    g83100.sswi_batch.end_active_date
FROM
         g83100.sswi_photo
    INNER JOIN g83100.sswi_camera ON g83100.sswi_photo.camera_seq_no = g83100.sswi_camera.camera_seq_no
    INNER JOIN g83100.sswi_cam_part_grid_xref ON g83100.sswi_camera.camera_seq_no = g83100.sswi_cam_part_grid_xref.camera_seq_no
    INNER JOIN g83100.sswi_partner ON g83100.sswi_cam_part_grid_xref.partner_seq_no = g83100.sswi_partner.partner_seq_no
    INNER JOIN g83100.sswi_batch ON g83100.sswi_photo.upload_batch_seq_no = g83100.sswi_batch.batch_seq_no
WHERE
    g83100.sswi_photo.camera_firmware_text = 'G5C2YL2006024'")


PhotosV4UpdateFirmware <- DBI::dbGetQuery(conn, "SELECT 
    g83100.sswi_photo.camera_firmware_text,
    g83100.sswi_photo.upload_batch_seq_no,
    g83100.sswi_photo.trigger_seq_no,
    g83100.sswi_photo.photo_seq_no,
    g83100.sswi_photo.camera_seq_no,
    g83100.sswi_photo.camera_location_seq_no
FROM
         g83100.sswi_photo
WHERE
    g83100.sswi_photo.camera_firmware_text = 'G5C2YL2006024'")


DTQC <- DBI::dbGetQuery(conn,"SELECT DISTINCT
g83100.sswi_photo.camera_firmware_text,
g83100.sswi_photo.upload_batch_seq_no,
g83100.sswi_photo.camera_seq_no,
g83100.sswi_batch.start_active_date,
g83100.sswi_batch.end_active_date,
g83100.sswi_dtqc_error.dtqc_error_code,
g83100.sswi_dtqc_error.corr_batch_start_date,
g83100.sswi_dtqc_error.corr_batch_end_date,
g83100.sswi_dtqc_error.comment_text
FROM
g83100.sswi_photo
INNER JOIN g83100.sswi_batch ON g83100.sswi_photo.upload_batch_seq_no = g83100.sswi_batch.batch_seq_no
INNER JOIN g83100.sswi_dtqc_error ON g83100.sswi_batch.batch_seq_no = g83100.sswi_dtqc_error.batch_seq_no
WHERE
g83100.sswi_photo.camera_firmware_text = 'G5C2YL2006024'")


```

## 
```{r}
PartnerV4UpdateFirmware%>%select(-PARTNER_COMMENT_TEXT)%>%distinct()%>%
   kableExtra::kbl() %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover")) %>%
  kableExtra::scroll_box(width = "100%", height = "300px")
```

## 7 BATCHES
```{r}
table(PhotosV4UpdateFirmware$UPLOAD_BATCH_SEQ_NO)

```

## One CAMERA (cam_seq_no)
```{r}
table(PhotosV4UpdateFirmware$CAMERA_SEQ_NO)
```


```{r Partner Comments Table, fig.width=10}
Comments <- data.frame("PartnerComments"=unique(PartnerV4UpdateFirmware$PARTNER_COMMENT_TEXT))
Comments$PartnerComments <- str_replace_all(string = Comments$PartnerComments, pattern = "()(?=\\d{1,2}\\/\\d{1,2}\\/\\d{2})", replacement = "\n")
        
        
        #make theme for table, only thing set is font size
mytheme <- gridExtra::ttheme_default(
  core = list(fg_params=list(cex = 0.7)), #fg_params = foreground parameters
  colhead = list(fg_params=list(cex = 0.78)),
  rowhead = list(fg_params=list(cex = 0.78)))
#turn table into a tableGrob (whatever that is) for input into ggplot object
CommentsGrob <- tableGrob(Comments, theme=mytheme, cols = c("Partner Comments"))

#make table a ggplot object
tableplot <- ggplot() + theme_void() + 
  annotation_custom(CommentsGrob)
tableplot
```

## DTQC
```{r}

```
